services:
  app:
    build:
      context: .
      dockerfile: WebApp.Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${ROUTER_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${ROUTER_NAME}.rule=Host(`${SERVER_NAME}`)"
      - "traefik.http.routers.${ROUTER_NAME}.tls=true"
      - "traefik.http.routers.${ROUTER_NAME}.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik-proxy"
    networks:
      - traefik-proxy
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

networks:
  traefik-proxy:
    driver: bridge
    external: true
